---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluent-bit
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/east-ga-jr-01/fluent-bit
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
