template: .gitops
deployments:
  dev:
    target: dev
    values:
      name: flux-system
      namespace: flux-system
      workspace: flux-system
      repo: joaquinrz/pib-gitops
      branch: main
      targets: [ all ]
